// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// Decode provides a mock function for the type MockHasher
func (_mock *MockHasher) Decode(code string) (int, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(code)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockHasher_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - code string
func (_e *MockHasher_Expecter) Decode(code interface{}) *MockHasher_Decode_Call {
	return &MockHasher_Decode_Call{Call: _e.mock.On("Decode", code)}
}

func (_c *MockHasher_Decode_Call) Run(run func(code string)) *MockHasher_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Decode_Call) Return(n int, err error) *MockHasher_Decode_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHasher_Decode_Call) RunAndReturn(run func(code string) (int, error)) *MockHasher_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function for the type MockHasher
func (_mock *MockHasher) Encode(id int) (string, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (string, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockHasher_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - id int
func (_e *MockHasher_Expecter) Encode(id interface{}) *MockHasher_Encode_Call {
	return &MockHasher_Encode_Call{Call: _e.mock.On("Encode", id)}
}

func (_c *MockHasher_Encode_Call) Run(run func(id int)) *MockHasher_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_Encode_Call) Return(s string, err error) *MockHasher_Encode_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_Encode_Call) RunAndReturn(run func(id int) (string, error)) *MockHasher_Encode_Call {
	_c.Call.Return(run)
	return _c
}
