// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/m-bromo/atom-ly/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkRepository creates a new instance of MockLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkRepository {
	mock := &MockLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkRepository is an autogenerated mock type for the LinkRepository type
type MockLinkRepository struct {
	mock.Mock
}

type MockLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkRepository) EXPECT() *MockLinkRepository_Expecter {
	return &MockLinkRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) GetByID(ctx context.Context, id int) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLinkRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockLinkRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLinkRepository_GetByID_Call {
	return &MockLinkRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLinkRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockLinkRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_GetByID_Call) Return(s string, err error) *MockLinkRepository_GetByID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLinkRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (string, error)) *MockLinkRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUrl provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) GetByUrl(ctx context.Context, url string) (int, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for GetByUrl")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_GetByUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUrl'
type MockLinkRepository_GetByUrl_Call struct {
	*mock.Call
}

// GetByUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockLinkRepository_Expecter) GetByUrl(ctx interface{}, url interface{}) *MockLinkRepository_GetByUrl_Call {
	return &MockLinkRepository_GetByUrl_Call{Call: _e.mock.On("GetByUrl", ctx, url)}
}

func (_c *MockLinkRepository_GetByUrl_Call) Run(run func(ctx context.Context, url string)) *MockLinkRepository_GetByUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_GetByUrl_Call) Return(n int, err error) *MockLinkRepository_GetByUrl_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLinkRepository_GetByUrl_Call) RunAndReturn(run func(ctx context.Context, url string) (int, error)) *MockLinkRepository_GetByUrl_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Save(ctx context.Context, link *entities.Link) (int, error) {
	ret := _mock.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Link) (int, error)); ok {
		return returnFunc(ctx, link)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Link) int); ok {
		r0 = returnFunc(ctx, link)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Link) error); ok {
		r1 = returnFunc(ctx, link)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - link *entities.Link
func (_e *MockLinkRepository_Expecter) Save(ctx interface{}, link interface{}) *MockLinkRepository_Save_Call {
	return &MockLinkRepository_Save_Call{Call: _e.mock.On("Save", ctx, link)}
}

func (_c *MockLinkRepository_Save_Call) Run(run func(ctx context.Context, link *entities.Link)) *MockLinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Link
		if args[1] != nil {
			arg1 = args[1].(*entities.Link)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Save_Call) Return(n int, err error) *MockLinkRepository_Save_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLinkRepository_Save_Call) RunAndReturn(run func(ctx context.Context, link *entities.Link) (int, error)) *MockLinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
