// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkService creates a new instance of MockLinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkService {
	mock := &MockLinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkService is an autogenerated mock type for the LinkService type
type MockLinkService struct {
	mock.Mock
}

type MockLinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkService) EXPECT() *MockLinkService_Expecter {
	return &MockLinkService_Expecter{mock: &_m.Mock}
}

// Redirect provides a mock function for the type MockLinkService
func (_mock *MockLinkService) Redirect(ctx context.Context, shortLink string) (string, error) {
	ret := _mock.Called(ctx, shortLink)

	if len(ret) == 0 {
		panic("no return value specified for Redirect")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, shortLink)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, shortLink)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortLink)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_Redirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redirect'
type MockLinkService_Redirect_Call struct {
	*mock.Call
}

// Redirect is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink string
func (_e *MockLinkService_Expecter) Redirect(ctx interface{}, shortLink interface{}) *MockLinkService_Redirect_Call {
	return &MockLinkService_Redirect_Call{Call: _e.mock.On("Redirect", ctx, shortLink)}
}

func (_c *MockLinkService_Redirect_Call) Run(run func(ctx context.Context, shortLink string)) *MockLinkService_Redirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkService_Redirect_Call) Return(s string, err error) *MockLinkService_Redirect_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLinkService_Redirect_Call) RunAndReturn(run func(ctx context.Context, shortLink string) (string, error)) *MockLinkService_Redirect_Call {
	_c.Call.Return(run)
	return _c
}

// ShortenLink provides a mock function for the type MockLinkService
func (_mock *MockLinkService) ShortenLink(ctx context.Context, url string) (string, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for ShortenLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_ShortenLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShortenLink'
type MockLinkService_ShortenLink_Call struct {
	*mock.Call
}

// ShortenLink is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockLinkService_Expecter) ShortenLink(ctx interface{}, url interface{}) *MockLinkService_ShortenLink_Call {
	return &MockLinkService_ShortenLink_Call{Call: _e.mock.On("ShortenLink", ctx, url)}
}

func (_c *MockLinkService_ShortenLink_Call) Run(run func(ctx context.Context, url string)) *MockLinkService_ShortenLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkService_ShortenLink_Call) Return(s string, err error) *MockLinkService_ShortenLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockLinkService_ShortenLink_Call) RunAndReturn(run func(ctx context.Context, url string) (string, error)) *MockLinkService_ShortenLink_Call {
	_c.Call.Return(run)
	return _c
}
