// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getByID = `-- name: GetByID :one
SELECT links.url
FROM links
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getByURl = `-- name: GetByURl :one
SELECT links.url
FROM links
WHERE url = $1
`

func (q *Queries) GetByURl(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRowContext(ctx, getByURl, url)
	err := row.Scan(&url)
	return url, err
}

const save = `-- name: Save :one
INSERT INTO links (
    url,
    created_at
) VALUES (
    $1, $2
) RETURNING id
`

type SaveParams struct {
	Url       string
	CreatedAt sql.NullTime
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, save, arg.Url, arg.CreatedAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}
