// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetByID(ctx context.Context, id int32) (string, error)
	GetIDByUrl(ctx context.Context, url string) (int32, error)
	Save(ctx context.Context, arg SaveParams) (int32, error)
}

var _ Querier = (*Queries)(nil)
